title: <p align="center"> Connor <br> Lewis-Smith </p> 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
 Social Scientist
   <br><br>
 Pacific States Marine Fisheries Commission in support of NOAA Fisheries Conservation Biology for the West Coast
  <br><br>
  <a href="www.linkedin.com/in/connorlewissmith">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-LNC8D5QH9E # your Google Analytics tracking ID here

