title: <p align="center"> Connor <br> Lewis-Smith </p> 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
<p align="center"> Social Scientist </p>

<p align="justify">
  <a href="www.linkedin.com/in/connorlewissmith">View My LinkedIn Profile</a> 
</p>
  
theme: jekyll-theme-minimal
google_analytics: G-LNC8D5QH9E # your Google Analytics tracking ID here

