title: Connor Lewis-Smith # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data Management Specialist with the Pacific States Marine Fisheries Commission in support of NOAA Fisheries Conservation Biology for the West Coast
  <br><br>
  <a href="www.linkedin.com/in/connorlewissmith">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-LNC8D5QH9E # your Google Analytics tracking ID here

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LNC8D5QH9E"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LNC8D5QH9E');
</script>
